combine rc and release workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -4,145 +4,147 @@ name: Release Design
 on:
   workflow_call:
 
-# ToDo:
-# - if any version number is over 9 then no release is in github only the tag. 
- 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
+  determine-release-type:
+    runs-on: ubuntu-latest
+    outputs:
+      release-type: ${{ steps.check-tag.outputs.release-type }}
+    steps:
+      - name: Check tag
+        id: check-tag
+        run: |
+          if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+$ ]]; then
+            echo "release-type=release" >> $GITHUB_OUTPUT
+          elif [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+-rc[0-9]+$ ]]; then
+            echo "release-type=rc" >> $GITHUB_OUTPUT
+          else
+            echo "Invalid tag format"
+            exit 1
+          fi
+
   ERC:
     runs-on: ubuntu-latest
-    container: ghcr.io/inti-cmnb/kicad6_auto:1.6.4
-
+    container: ghcr.io/inti-cmnb/kicad8_auto:1.7.0
     steps:
-    - uses: actions/checkout@v4
-
-    - name: Run ERC
-      run: |
-        [ -f *.kicad_sch ] && kiplot  -d Fabrication_temp -s update_xml,run_drc -i
-    # - name: Retrieve results
-    #   uses: actions/upload-artifact@v1
-    #   with:
-    #     name: ERC_Output
-    #     path: Fabrication_temp
+      - uses: actions/checkout@v4
+      - name: Run ERC
+        run: |
+          [ -f *.kicad_sch ] && kiplot  -d Fabrication_temp -s update_xml,run_drc -i
 
   DRC:
     runs-on: ubuntu-latest
-    container: ghcr.io/inti-cmnb/kicad6_auto:1.6.4
+    container: ghcr.io/inti-cmnb/kicad8_auto:1.7.0
     needs: ERC
-
     steps:
-    - uses: actions/checkout@v4
+      - uses: actions/checkout@v4
+      - name: Run DRC
+        run: |
+          [ -f *.kicad_pcb ] && kiplot  -d Fabrication_temp -s update_xml,run_erc -i
 
-    - name: Run DRC
-      run: |
-        [ -f *.kicad_pcb ] && kiplot  -d Fabrication_temp -s update_xml,run_erc -i
-    # - name: Retrieve results
-    #   uses: actions/upload-artifact@v1
-    #   with:
-    #     name: DRC_Output
-    #     path: Fabrication_temp
-    
-  FabSch:
+  Fabrication:
     name: Fabrication files
     runs-on: ubuntu-latest
     permissions:
       contents: write
-    container: ghcr.io/inti-cmnb/kicad6_auto:1.6.4
-    needs: DRC
-
+    container: ghcr.io/inti-cmnb/kicad8_auto:1.7.0
+    needs: [DRC, determine-release-type]
     steps:
-    - name: Update system repositories, Install Required Libraries
-      run: |
-        apt update
-        apt -y install git
-    
-    - name: Checkout Repository
-      uses: actions/checkout@v4
+      - name: Update system repositories, Install Required Libraries
+        run: |
+          apt update
+          apt -y install git
+      
+      - name: Checkout Repository
+        uses: actions/checkout@v4
 
-    - name: Assign variables from project.properties to Env variable
-      run: |
-        cat project.properties | egrep -v "^\s*(#|$)" >> $GITHUB_ENV 
-    
-    - name: Update the Schematic with the git hash
-      run: |
-        export COMMIT=$(git rev-parse --short HEAD)
-        echo "COMMIT = ${COMMIT}"
-        sed -i "s!<<hash>>!Git-${COMMIT}!" *.kicad_sch
-        sed -i "s!<<project_name>>!${{ env.project_name }}!" *.kicad_sch
-        sed -i "s!<<date>>!$(date +'%Y-%m-%d')!" *.kicad_sch 
-        sed -i "s!<<version>>!${{ github.ref_name }}!" *.kicad_sch 
-        sed -i "s!<<ID>>!ID:${{ env.ID_prefix }}${{ env.ID }}!" *.kicad_sch
-        mv *.kicad_sch ${{ env.ID_prefix }}${{ env.ID }}_${{ env.project_name }}_${{ github.ref_name }}.kicad_sch
+      - name: Assign variables from project.properties to Env variable
+        run: |
+          cat project.properties | egrep -v "^\s*(#|$)" >> $GITHUB_ENV 
+      
+      - name: Update the Schematic with the git hash
+        run: |
+          export COMMIT=$(git rev-parse --short HEAD)
+          echo "COMMIT = ${COMMIT}"
+          sed -i "s!<<hash>>!Git-${COMMIT}!" *.kicad_sch
+          sed -i "s!<<project_name>>!${{ env.project_name }}!" *.kicad_sch
+          sed -i "s!<<date>>!$(date +'%Y-%m-%d')!" *.kicad_sch 
+          sed -i "s!<<version>>!${{ github.ref_name }}!" *.kicad_sch 
+          sed -i "s!<<ID>>!ID:${{ env.ID_prefix }}${{ env.ID }}!" *.kicad_sch
+          mv *.kicad_sch ${{ env.ID_prefix }}${{ env.ID }}_${{ env.project_name }}_${{ github.ref_name }}.kicad_sch
 
-    - name: Update the PCBs with the git hash
-      run: |
-        export COMMIT=$(git rev-parse --short HEAD)
-        echo "COMMIT = ${COMMIT}"
-        sed -i "s!<<hash>>!Git-${COMMIT}!" *.kicad_pcb
-        sed -i "s!<<project_name>>!${{ env.project_name }}!" *.kicad_pcb
-        sed -i "s!<<date>>!$(date +'%Y-%m-%d')!" *.kicad_pcb 
-        sed -i "s!<<version>>!${{ github.ref_name }}!" *.kicad_pcb 
-        sed -i "s!<<ID>>!ID:${{ env.ID_prefix }}${{ env.ID }}!" *.kicad_pcb
-        sed -i "s!<<website_link>>!${{ env.Website_link }}/${{ env.ID_prefix }}/${{ env.ID }}!" *.kicad_pcb 
-        mv *.kicad_pcb ${{ env.ID_prefix }}${{ env.ID }}_${{ env.project_name }}_${{ github.ref_name }}.kicad_pcb
+      - name: Update the PCBs with the git hash
+        run: |
+          export COMMIT=$(git rev-parse --short HEAD)
+          echo "COMMIT = ${COMMIT}"
+          sed -i "s!<<hash>>!Git-${COMMIT}!" *.kicad_pcb
+          sed -i "s!<<project_name>>!${{ env.project_name }}!" *.kicad_pcb
+          sed -i "s!<<date>>!$(date +'%Y-%m-%d')!" *.kicad_pcb 
+          sed -i "s!<<version>>!${{ github.ref_name }}!" *.kicad_pcb 
+          sed -i "s!<<ID>>!ID:${{ env.ID_prefix }}${{ env.ID }}!" *.kicad_pcb
+          sed -i "s!<<website_link>>!${{ env.Website_link }}/${{ env.ID_prefix }}/${{ env.ID }}!" *.kicad_pcb 
+          mv *.kicad_pcb ${{ env.ID_prefix }}${{ env.ID }}_${{ env.project_name }}_${{ github.ref_name }}.kicad_pcb
 
-    - name: Update the release note with the RepoName / Tag
-      run: |
-        sed -i "s!<<repo_name>>!${{ github.repository }}!g" docs/release_note.md
-        sed -i "s!<<tag>>!${{ github.ref_name }}!g" docs/release_note.md
-        sed -i "s!<<project_name>>!${{ env.project_name }}!g" docs/release_note.md
-        sed -i "s!<<version>>!${{ github.ref_name }}!g" docs/release_note.md
-        sed -i "s!<<ID>>!${{ env.ID_prefix }}${{ env.ID }}!g" docs/release_note.md
+      - name: Update the release note with the RepoName / Tag
+        run: |
+          sed -i "s!<<repo_name>>!${{ github.repository }}!g" docs/release_note.md
+          sed -i "s!<<tag>>!${{ github.ref_name }}!g" docs/release_note.md
+          sed -i "s!<<project_name>>!${{ env.project_name }}!g" docs/release_note.md
+          sed -i "s!<<version>>!${{ github.ref_name }}!g" docs/release_note.md
+          sed -i "s!<<ID>>!${{ env.ID_prefix }}${{ env.ID }}!g" docs/release_note.md
 
-    - name: Run Schematic and BOM 
-      run: |
-        [ -f *.kicad_sch ] && kiplot -d Fabrication_temp -s all  print_sch interactive_bom bom_csv_release
-        head -n -12 Fabrication_temp/BoM-long.csv > Fabrication_temp/BoM.csv
+      - name: Run Schematic and BOM 
+        run: |
+          [ -f *.kicad_sch ] && kiplot -d Fabrication_temp -s all  print_sch interactive_bom 
+          if [[ "${{ needs.determine-release-type.outputs.release-type }}" == "release" ]]; then
+            kiplot -d Fabrication_temp -s all bom_csv_release
+            head -n -12 Fabrication_temp/BoM-long.csv > Fabrication_temp/BoM.csv
+          fi
 
-    - name: Run PCB
-      run: |
-        [ -f *.kicad_pcb ] && kiplot  -d Fabrication_temp -s all print_front print_back pcb_top_b pcb_bottom_b step 3dview
+      - name: Run PCB
+        run: |
+          [ -f *.kicad_pcb ] && kiplot  -d Fabrication_temp -s all print_front print_back pcb_top_b pcb_bottom_b step 3dview
 
-    - name: Run Gerber
-      run: |
-        [ -f *.kicad_pcb ] && kiplot  -d Gerber -s all gerbers gerber_drills
+      - name: Run Gerber
+        run: |
+          [ -f *.kicad_pcb ] && kiplot  -d Gerber -s all gerbers gerber_drills
 
-    - name: Renaming Files
-      run: |
-        cd Fabrication_temp
-        for file in *; do mv -v ${file} ${{ env.ID_prefix }}${{ env.ID }}_${{ env.project_name }}_${{ github.ref_name }}_${file}; done #https://unix.stackexchange.com/a/389516
+      - name: Renaming Files
+        run: |
+          cd Fabrication_temp
+          for file in *; do mv -v ${file} ${{ env.ID_prefix }}${{ env.ID }}_${{ env.project_name }}_${{ github.ref_name }}_${file}; done
 
-    - uses: vimtor/action-zip@v1.1
-      with:
-        files: Gerber/
-        recursive: false
-        dest: ${{ env.ID_prefix }}${{ env.ID }}_${{ env.project_name }}_${{ github.ref_name }}_Gerber.zip
+      - uses: vimtor/action-zip@v1.1
+        with:
+          files: Gerber/
+          recursive: false
+          dest: ${{ env.ID_prefix }}${{ env.ID }}_${{ env.project_name }}_${{ github.ref_name }}_Gerber.zip
 
-    - uses: ncipollo/release-action@v1
-      with:
-        artifacts: "Fabrication_temp/*, *.kicad_sch, *.kicad_pcb, *Gerber.zip, *.csv "
-        bodyFile: "docs/release_note.md"
-        token: ${{ secrets.GITHUB_TOKEN }}
+      - uses: ncipollo/release-action@v1
+        with:
+          artifacts: "Fabrication_temp/*, *.kicad_sch, *.kicad_pcb, *Gerber.zip"
+          bodyFile: "docs/release_note.md"
+          prerelease: ${{ needs.determine-release-type.outputs.release-type == 'rc' }}
+          token: ${{ secrets.GITHUB_TOKEN }}
 
   Archiv-md:
     name: Archive & Renew Release Docs
     runs-on: ubuntu-latest
-    needs: FabSch
+    needs: [Fabrication, determine-release-type]
+    if: needs.determine-release-type.outputs.release-type == 'release'
     steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
 
-    - name: Checkout Repository
-      uses: actions/checkout@v4
+      - name: Renaming Release note & checklist + copy the template
+        run: |
+          cd docs
+          mv release_note.md release_note_${{ github.ref_name }}.md
+          mv release_checklist.md release_checklist_${{ github.ref_name }}.md
+          cp release_template/release_note.md release_note.md 
+          cp release_template/release_checklist.md release_checklist.md
 
-    - name: Renaming Release note & checklist + copy the template
-      run: |
-        cd docs
-        mv release_note.md release_note_${{ github.ref_name }}.md
-        mv release_checklist.md release_checklist_${{ github.ref_name }}.md
-        cp release_template/release_note.md release_note.md 
-        cp release_template/release_checklist.md release_checklist.md
-
-    - uses: stefanzweifel/git-auto-commit-action@v5
-      with:
-        repository: .
-        branch: main
-        commit_message: Archive & Renew release docs
+      - uses: stefanzweifel/git-auto-commit-action@v5
+        with:
+          repository: .
+          branch: main
+          commit_message: Archive & Renew release docs
